#!/bin/bash -l
#SBATCH -N 1                # you'll never need more than 1 node for the serial code        # adjust the amount of time as necessary
#SBATCH -J auto-openmp32
#SBATCH -o auto-openmp32.%j.stdout
#SBATCH -e auto-openmp32.%j.error

rm openmp.txt
./serial -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=1
./openmp -p 1 -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=2
./openmp -p 2 -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=4
./openmp -p 4 -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=6
./openmp -p 6 -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=12
./openmp -p 12 -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=18
./openmp -p 18 -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=24
./openmp -p 24 -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=32
./openmp -p 32 -n 5000 -no -s openmp.txt
export OMP_NUM_THREADS=2
./openmp -p 2 -n 10000 -no -s openmp.txt
export OMP_NUM_THREADS=4
./openmp -p 4 -n 20000 -no -s openmp.txt
export OMP_NUM_THREADS=6
./openmp -p 6 -n 30000 -no -s openmp.txt
export OMP_NUM_THREADS=12
./openmp -p 12 -n 60000 -no -s openmp.txt
export OMP_NUM_THREADS=18
./openmp -p 18 -n 90000 -no -s openmp.txt
export OMP_NUM_THREADS=24
./openmp -p 24 -n 120000 -no -s openmp.txt
export OMP_NUM_THREADS=32
./openmp -p 32 -n 160000 -no -s openmp.txt
./autograder -v openmp -s openmp.txt
